import "./style.css";
import { loadNaics } from "./naics/loader.ts";
import { classifyConfidence } from "./naics/confidence.ts";
import { drilldownOptions, getNode, isResolved } from "./naics/drilldown.ts";
import type { HierarchyTree } from "./naics/hierarchy.ts";
import type { NaicsScore } from "./naics/beacon-model.ts";

document.querySelector<HTMLDivElement>("#app")!.innerHTML = `
<section id="resolver">
  <h1>NAICS Code Resolver</h1>
  <p>Describe your business. We'll match it to a 6-digit NAICS code. <a href="#how-it-works">How does it work?</a></p>
  <form id="naics-form">
    <input id="naics-input" type="search" placeholder="e.g. retail bakery" autocomplete="off" />
    <button id="naics-submit" type="submit">Find code</button>
  </form>
  <div id="naics-result" hidden></div>
  <div id="naics-qa" hidden></div>
</section>

<section id="how-it-works">
  <h2>How does it work?</h2>
  <p>
    Everything runs in your browser — no server, no API calls, no data leaves
    your machine. A ~5MB model file (a TypeScript port of the
    <a href="https://github.com/uscensusbureau/beacon" target="_blank" rel="noopener">Census Bureau's BEACON model</a>)
    loads on page load and scores your description against all ~1,000
    six-digit NAICS codes using n-gram matching, entirely client-side.
  </p>
  <svg viewBox="0 0 600 340" role="img" aria-label="Flow diagram: description typed, scored client-side against the NAICS codes, then either shown directly (high confidence) or narrowed via Q&amp;A (medium/low confidence), ending in a confirmed 6-digit code.">
    <defs>
      <marker id="arrow" markerWidth="8" markerHeight="8" refX="4" refY="4" orient="auto">
        <path d="M0,0 L8,4 L0,8 z" fill="var(--text)" />
      </marker>
    </defs>
    <g fill="none" stroke="var(--border)" stroke-width="1.5">
      <rect x="180" y="10" width="240" height="44" rx="6" />
      <rect x="180" y="90" width="240" height="54" rx="6" />
      <rect x="30" y="190" width="240" height="54" rx="6" />
      <rect x="330" y="190" width="240" height="54" rx="6" />
      <rect x="180" y="286" width="240" height="44" rx="6" />
    </g>
    <g fill="var(--text-h)" font-family="var(--sans)" font-size="14" text-anchor="middle">
      <text x="300" y="37">Type a business description</text>
      <text x="300" y="112">Scored client-side against ~1,000</text>
      <text x="300" y="130">NAICS codes (ported BEACON model)</text>
      <text x="150" y="212">High confidence (≥.70)</text>
      <text x="150" y="230">→ code shown directly</text>
      <text x="450" y="212">Medium/low confidence</text>
      <text x="450" y="230">→ Q&amp;A narrows it down</text>
      <text x="300" y="312">Confirmed 6-digit NAICS code</text>
    </g>
    <g stroke="var(--text)" stroke-width="1.5" marker-end="url(#arrow)">
      <line x1="300" y1="54" x2="300" y2="86" />
      <line x1="260" y1="144" x2="160" y2="186" />
      <line x1="340" y1="144" x2="440" y2="186" />
      <line x1="150" y1="244" x2="270" y2="282" />
      <line x1="450" y1="244" x2="330" y2="282" />
    </g>
  </svg>
  <p>
    Medium/low-confidence results offer the model's own top candidate codes
    as picks; picking one confirms it, or you can browse the full official
    NAICS hierarchy from the top down (sector → subsector → … → national
    industry) until a single 6-digit code is confirmed. All confidence
    thresholds and the NAICS hierarchy itself come from the official Census
    Bureau data — nothing is generated by a model or an LLM.
  </p>
</section>
`;

const form = document.querySelector<HTMLFormElement>("#naics-form")!;
const input = document.querySelector<HTMLInputElement>("#naics-input")!;
const resultEl = document.querySelector<HTMLDivElement>("#naics-result")!;
const qaEl = document.querySelector<HTMLDivElement>("#naics-qa")!;

// Kicked off on mount, never awaited by input handling (§V4) — submit awaits
// this same in-flight promise if it lands early (§V5, loader dedupes it).
const loaded = loadNaics();

// §V10: definition/examples optional — missing ones just don't render, never a blank/crash.
function snippet(text: string, max = 160): string {
  return text.length > max ? `${text.slice(0, max).trimEnd()}…` : text;
}

function renderResult(
  code: string,
  hierarchy: HierarchyTree,
  titles: Map<string, string>,
  score: number,
  label: string,
) {
  const node = getNode(hierarchy, code);
  const title = node?.title ?? titles.get(code) ?? "";
  resultEl.hidden = false;
  resultEl.innerHTML = `
    <p class="code">${code}</p>
    <p class="title">${title}</p>
    <p class="confidence">confidence: ${score.toFixed(2)} (${label})</p>
    ${node?.definition ? `<p class="definition">${node.definition}</p>` : ""}
    ${node?.examples?.length ? `<ul class="examples">${node.examples.map((e) => `<li>${e}</li>`).join("")}</ul>` : ""}
  `;
}

// §C: clarifying Q&A = static hierarchy drill-down only, ⊥ model/LLM-generated questions.
function renderHierarchyQA(
  hierarchy: HierarchyTree,
  titles: Map<string, string>,
  code: string | null,
) {
  const options = drilldownOptions(hierarchy, code);
  qaEl.innerHTML = `
    <p>Narrow it down:</p>
    <ul>${options.map((o) => `<li><button type="button" data-code="${o.code}">${o.title}</button></li>`).join("")}</ul>
  `;
  for (const btn of qaEl.querySelectorAll<HTMLButtonElement>("button[data-code]")) {
    btn.addEventListener("click", () => {
      const nextCode = btn.dataset.code!;
      if (isResolved(hierarchy, nextCode)) {
        renderResult(nextCode, hierarchy, titles, 1, "high"); // §V3: confirmed leaf is a valid 6-digit code
        qaEl.hidden = true;
      } else {
        renderHierarchyQA(hierarchy, titles, nextCode);
      }
    });
  }
}

// §V9: Q&A first offers the model's own top-N candidates, not the full hierarchy.
// Candidate picks show a definition snippet (§V10: absent -> just the title) to help choose.
function renderQA(candidates: NaicsScore[], hierarchy: HierarchyTree, titles: Map<string, string>) {
  qaEl.hidden = false;
  qaEl.innerHTML = `
    <p>Not quite right? Did you mean:</p>
    <ul>${candidates
      .map((c) => {
        const node = getNode(hierarchy, c.naics);
        const title = node?.title ?? titles.get(c.naics) ?? c.naics;
        const def = node?.definition ? `<p class="definition">${snippet(node.definition)}</p>` : "";
        return `<li><button type="button" data-code="${c.naics}">${title}${def}</button></li>`;
      })
      .join("")}</ul>
    <button type="button" id="naics-qa-browse">None of these — browse full hierarchy</button>
  `;
  for (const btn of qaEl.querySelectorAll<HTMLButtonElement>("button[data-code]")) {
    btn.addEventListener("click", () => {
      const code = btn.dataset.code!;
      if (isResolved(hierarchy, code)) {
        const candidate = candidates.find((c) => c.naics === code)!;
        renderResult(
          code,
          hierarchy,
          titles,
          candidate.score,
          classifyConfidence(candidate.score, undefined).label,
        );
        qaEl.hidden = true;
      } else {
        renderHierarchyQA(hierarchy, titles, code);
      }
    });
  }
  qaEl.querySelector<HTMLButtonElement>("#naics-qa-browse")!.addEventListener("click", () => {
    renderHierarchyQA(hierarchy, titles, null);
  });
}

async function handleSubmit(text: string) {
  const { model, titles, hierarchy } = await loaded; // §V5: await in-flight load, never drop/error
  qaEl.hidden = true;
  const top = model.predictTopN(text, 5);
  if (top.length === 0) {
    resultEl.hidden = false;
    resultEl.innerHTML = `<p>No match found. Try a different description.</p>`;
    return;
  }
  const { label, offerQA } = classifyConfidence(top[0].score, top[1]?.score);
  renderResult(top[0].naics, hierarchy, titles, top[0].score, label); // §V2/§V8: result always shown first
  if (offerQA) renderQA(top, hierarchy, titles);
}

form.addEventListener("submit", (event) => {
  event.preventDefault();
  const text = input.value.trim();
  if (text) void handleSubmit(text);
});
